wget http://www.currencysymbols.in/flags/afghanistan.png -O AFN.png
wget http://www.currencysymbols.in/flags/argentina.png -O ARS.png
wget http://www.currencysymbols.in/flags/aruba.png -O AWG.png
wget http://www.currencysymbols.in/flags/australia.png -O AUD.png
wget http://www.currencysymbols.in/flags/azerbaijan.png -O AZN.png
wget http://www.currencysymbols.in/flags/bahamas.png -O BSD.png
wget http://www.currencysymbols.in/flags/barbados.png -O BBD.png
wget http://www.currencysymbols.in/flags/belarus.png -O BYR.png
wget http://www.currencysymbols.in/flags/belize.png -O BZD.png
wget http://www.currencysymbols.in/flags/bermuda.png -O BMD.png
wget http://www.currencysymbols.in/flags/bolivia.png -O BOB.png
wget http://www.currencysymbols.in/flags/Bosnia_and_Herzegovina.png -O BAM.png
wget http://www.currencysymbols.in/flags/botswana.png -O BWP.png
wget http://www.currencysymbols.in/flags/bulgaria.png -O BGN.png
wget http://www.currencysymbols.in/flags/brazil.png -O BRL.png
wget http://www.currencysymbols.in/flags/brunei.png -O BND.png
wget http://www.currencysymbols.in/flags/cambodia.png -O KHR.png
wget http://www.currencysymbols.in/flags/canada.png -O CAD.png
wget http://www.currencysymbols.in/flags/Cayman_Islands.png -O KYD.png
wget http://www.currencysymbols.in/flags/chile.png -O CLP.png
wget http://www.currencysymbols.in/flags/china.png -O CNY.png
wget http://www.currencysymbols.in/flags/colombia.png -O COP.png
wget http://www.currencysymbols.in/flags/costarica.png -O CRC.png
wget http://www.currencysymbols.in/flags/croatia.png -O HRK.png
wget http://www.currencysymbols.in/flags/cuba.png -O CUP.png
wget http://www.currencysymbols.in/flags/czechrepublic.png -O CZK.png
wget http://www.currencysymbols.in/flags/denmark.png -O DKK.png
wget http://www.currencysymbols.in/flags/dominicanrepublic.png -O DOP.png
wget http://www.currencysymbols.in/flags/egypt.png -O EGP.png
wget http://www.currencysymbols.in/flags/elsalvador.png -O SVC.png
wget http://www.currencysymbols.in/flags/estonia.png -O EEK.png
wget http://www.currencysymbols.in/flags/euro.png -O EUR.png
wget http://www.currencysymbols.in/flags/falklandislands.png -O FKP.png
wget http://www.currencysymbols.in/flags/fiji.png -O FJD.png
wget http://www.currencysymbols.in/flags/ghana.png -O GHC.png
wget http://www.currencysymbols.in/flags/gibraltar.png -O GIP.png
wget http://www.currencysymbols.in/flags/guatemala.png -O GTQ.png
wget http://www.currencysymbols.in/flags/guernsey.png -O GGP.png
wget http://www.currencysymbols.in/flags/guyana.png -O GYD.png
wget http://www.currencysymbols.in/flags/honduras.png -O HNL.png
wget http://www.currencysymbols.in/flags/hongkong.png -O HKD.png
wget http://www.currencysymbols.in/flags/hungary.png -O HUF.png
wget http://www.currencysymbols.in/flags/iceland.png -O ISK.png
wget http://www.currencysymbols.in/flags/india.png -O INR.png
wget http://www.currencysymbols.in/flags/indonesia.png -O IDR.png
wget http://www.currencysymbols.in/flags/iran.png -O IRR.png
wget http://www.currencysymbols.in/flags/isleofman.png -O IMP.png
wget http://www.currencysymbols.in/flags/israel.png -O ILS.png
wget http://www.currencysymbols.in/flags/jamaica.png -O JMD.png
wget http://www.currencysymbols.in/flags/japan.png -O JPY.png
wget http://www.currencysymbols.in/flags/jersey.png -O JEP.png
wget http://www.currencysymbols.in/flags/kazakhstan.png -O KZT.png
wget http://www.currencysymbols.in/flags/northkorea.png -O KPW.png
wget http://www.currencysymbols.in/flags/southkorea.png -O KRW.png
wget http://www.currencysymbols.in/flags/kyrgyzstan.png -O KGS.png
wget http://www.currencysymbols.in/flags/laos.png -O LAK.png
wget http://www.currencysymbols.in/flags/latvia.png -O LVL.png
wget http://www.currencysymbols.in/flags/lebanon.png -O LBP.png
wget http://www.currencysymbols.in/flags/liberia.png -O LRD.png
wget http://www.currencysymbols.in/flags/lithuania.png -O LTL.png
wget http://www.currencysymbols.in/flags/macedonia.png -O MKD.png
wget http://www.currencysymbols.in/flags/malaysia.png -O MYR.png
wget http://www.currencysymbols.in/flags/mauritius.png -O MUR.png
wget http://www.currencysymbols.in/flags/mexico.png -O MXN.png
wget http://www.currencysymbols.in/flags/mongolia.png -O MNT.png
wget http://www.currencysymbols.in/flags/mozambique.png -O MZN.png
wget http://www.currencysymbols.in/flags/namibia.png -O NAD.png
wget http://www.currencysymbols.in/flags/nepal.png -O NPR.png
wget http://www.currencysymbols.in/flags/netherlands.png -O ANG.png
wget http://www.currencysymbols.in/flags/newzealand.png -O NZD.png
wget http://www.currencysymbols.in/flags/nicaragua.png -O NIO.png
wget http://www.currencysymbols.in/flags/nigeria.png -O NGN.png
wget http://www.currencysymbols.in/flags/norway.png -O NOK.png
wget http://www.currencysymbols.in/flags/oman.png -O OMR.png
wget http://www.currencysymbols.in/flags/pakistan.png -O PKR.png
wget http://www.currencysymbols.in/flags/panama.png -O PAB.png
wget http://www.currencysymbols.in/flags/paraguay.png -O PYG.png
wget http://www.currencysymbols.in/flags/peru.png -O PEN.png
wget http://www.currencysymbols.in/flags/philippines.png -O PHP.png
wget http://www.currencysymbols.in/flags/poland.png -O PLN.png
wget http://www.currencysymbols.in/flags/qatar.png -O QAR.png
wget http://www.currencysymbols.in/flags/romania.png -O RON.png
wget http://www.currencysymbols.in/flags/russia.png -O RUB.png
wget http://www.currencysymbols.in/flags/sainthelena.png -O SHP.png
wget http://www.currencysymbols.in/flags/saudiarabia.png -O SAR.png
wget http://www.currencysymbols.in/flags/serbia.png -O RSD.png
wget http://www.currencysymbols.in/flags/seychelles.png -O SCR.png
wget http://www.currencysymbols.in/flags/singapore.png -O SGD.png
wget http://www.currencysymbols.in/flags/solomonislands.png -O SBD.png
wget http://www.currencysymbols.in/flags/somalia.png -O SOS.png
wget http://www.currencysymbols.in/flags/southafrica.png -O ZAR.png
wget http://www.currencysymbols.in/flags/srilanka.png -O LKR.png
wget http://www.currencysymbols.in/flags/sweden.png -O SEK.png
wget http://www.currencysymbols.in/flags/switzerland.png -O CHF.png
wget http://www.currencysymbols.in/flags/suriname.png -O SRD.png
wget http://www.currencysymbols.in/flags/syria.png -O SYP.png
wget http://www.currencysymbols.in/flags/taiwan.png -O TWD.png
wget http://www.currencysymbols.in/flags/thailand.png -O THB.png
wget http://www.currencysymbols.in/flags/trinidadandtobago.png -O TTD.png
wget http://www.currencysymbols.in/flags/turkey.png -O TRL.png
wget http://www.currencysymbols.in/flags/tuvalu.png -O TVD.png
wget http://www.currencysymbols.in/flags/ukraine.png -O UAH.png
wget http://www.currencysymbols.in/flags/unitedkingdom.png -O GBP.png
wget http://www.currencysymbols.in/flags/unitedstates.png -O USD.png
wget http://www.currencysymbols.in/flags/uruguay.png -O UYU.png
wget http://www.currencysymbols.in/flags/uzbekistan.png -O UZS.png
wget http://www.currencysymbols.in/flags/venezuela.png -O VEF.png
wget http://www.currencysymbols.in/flags/vietnam.png -O VND.png
wget http://www.currencysymbols.in/flags/yemen.png -O YER.png
wget http://www.currencysymbols.in/flags/zimbabwe.png -O ZWD.png
wget http://www.currencysymbols.in/flags/turkey.png -O TRY.png

